# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phenovis_adjust_lab <- function(image_path, l_star_mean, l_p25, l_p75, l_factor, a_star_mean, a_p25, a_p75, a_factor, b_star_mean, b_p25, b_p75, b_factor) {
    .Call(`_phenovisr_phenovis_adjust_lab`, image_path, l_star_mean, l_p25, l_p75, l_factor, a_star_mean, a_p25, a_p75, a_factor, b_star_mean, b_p25, b_p75, b_factor)
}

phenovis_lab_stats <- function(images) {
    .Call(`_phenovisr_phenovis_lab_stats`, images)
}

phenovis_adjust_lstar <- function(image_path, l_star_mean, l_star_std_dev, factor) {
    .Call(`_phenovisr_phenovis_adjust_lstar`, image_path, l_star_mean, l_star_std_dev, factor)
}

phenovis_read_mask <- function(maskname) {
    invisible(.Call(`_phenovisr_phenovis_read_mask`, maskname))
}

phenovis_read_masks <- function(maskNames) {
    invisible(.Call(`_phenovisr_phenovis_read_masks`, maskNames))
}

phenovis_get_mean_L_star <- function(images) {
    .Call(`_phenovisr_phenovis_get_mean_L_star`, images)
}

phenovis_get_mean_gcc <- function(images) {
    .Call(`_phenovisr_phenovis_get_mean_gcc`, images)
}

phenovis_get_moving_window <- function(images) {
    .Call(`_phenovisr_phenovis_get_moving_window`, images)
}

phenovis_get_mean_all_metrics <- function(images) {
    .Call(`_phenovisr_phenovis_get_mean_all_metrics`, images)
}

phenovis_get_boost_stats <- function(images) {
    .Call(`_phenovisr_phenovis_get_boost_stats`, images)
}

phenovis_get_metrics <- function(images) {
    .Call(`_phenovisr_phenovis_get_metrics`, images)
}

phenovis_multimask_get_metrics <- function(images, maskIndexes) {
    .Call(`_phenovisr_phenovis_multimask_get_metrics`, images, maskIndexes)
}

